### ISSUE TITLE
Modal support

### ISSUE THREAD

**Issue by okbody39** [daviddang91/react-native-redux-starter-kit#1]
Will you support Modal navigation?

**Comment by daviddang91** [comment]
Hi @okbody39 

Thank for your suggestion.

I will support Modal navigation. but currently, I'm busy with another project. So, I'm very happy if you can help me integrate Redux Modal to this project.

Thanks,
David

**Comment by daviddang91** [comment]
Hi,
I did integrate redux modal to this project.
Thanks
