### ISSUE TITLE
Invalid Version - package.json when running npm start

### ISSUE THREAD

**Issue by paulkevany** [daviddang91/react-native-redux-starter-kit#10]
After doing git clone and attempting to run with **npm start**, an error message is outputted. The message states: Invalid version: "2.7.2.57". This happens when running either **npm install** or **npm start**. 
I was able to run npm install after i reverted the version in package.json from _2.7.2.57_ to _2.7.0_.

**Comment by daviddang91** [comment]
Thanks for your report. I have updated it.
